### ISSUE TITLE
Getting Error "Direct template access is not allowed"

### ISSUE THREAD

**Issue by vivekkiran** [mozilla/One-Mozilla-blog#11]

**Comment by MikkCZ** [comment]
This error message should be shown only when accessing the [index.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/index.php) directly, which is IMO desired behavior. Maybe changing the code to `defined( 'ABSPATH' ) or die( 'Direct template access is not allowed' );` only worth considering according to [Writing a Plugin « WordPress Codex](https://codex.wordpress.org/Writing_a_Plugin#Plugin_Files), but I suppose this issue can be closed as WONTFIX.

**Comment by craigcook** [comment]
Correct, this is intentional to block direct access attempts. We could check for ABSPATH and/or change exit to die, but they have the same effect in the end. I'm calling this issue a wontfix.
