### ISSUE TITLE
Bug 1093562 - Add a Twitter account field for sharing

### ISSUE THREAD

**Issue by craigcook** [mozilla/One-Mozilla-blog#16]
Filing an issue to nag myself to work on this. https://bugzilla.mozilla.org/show_bug.cgi?id=1093562

It will require adding another option field for twitter account and passing that value into the share widget where it's embedded (with a data attribute).

**Comment by MikkCZ** [comment]
@craigcook Are you working on this?

**Comment by craigcook** [comment]
> @craigcook Are you working on this?

Not at the moment. The social sharing widget integrated into the theme is frankly really outdated and a bit clunky, and I've wanted to revisit it for a long time but just never have. I was putting off adding the field because I wanted to overhaul that sharing widget at the same time, but there's really no reason not to add the field separately. If you'd like to work on this, by all means feel free. 😃

**Comment by MikkCZ** [comment]
Yes, I would like to take this. Do you have the original (no minified) version of socialshare.min.js, please?

**Comment by craigcook** [comment]
You can find the original SocialShare widget in its own repository at https://github.com/mozilla/SocialShare and the unminimized .js file at https://github.com/mozilla/SocialShare/blob/master/src/socialshare.js

That project has been mostly abandoned and we're free to deviate from the original here so if you need to make any changes to the JavaScript I think you can add the unminimized script into the theme, along with a newly minimized version based on what you've changed. Adding a twitter field might not even require any script changes, we might only have to put its value into the page's metadata.

That said, I think we could also explore other options for social sharing in the One Mozilla theme. The sharing widget was created as a way of including the "official" buttons for Twitter, Facebook, and G+ in a way that didn't load scripts from offsite that would track users. But we can also implement social sharing that just doesn't use the official buttons and only uses static links (that's what I'm doing in a new theme I'm working on). I think perhaps the complexity of using the official buttons in a way that respects user privacy outweighs any benefit those official buttons give us (they show the number of tweets/likes but I'm not sure users really care about those stats).

So if you start to dig into adding a twitter field and find that the sharing widget complicates things, maybe we can simplify the widget 😄

**Comment by MikkCZ** [comment]
Resolved by https://github.com/mozilla/One-Mozilla-blog/pull/57
