### ISSUE TITLE
Missing strings in onemozilla.pot file

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/One-Mozilla-blog#22]
Hi. I was unable to find 'One response'/'%d responses' string in the l10n files (onemozilla.pot
). Maybe other strings could be missing, but haven't noticed so far.

The string is here: https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/comments.php#L29

**Comment by MikkCZ** [comment]
There are more strings missing in the `onemozilla.pot` file.
- `Permanent link to &ldquo;%s&rdquo;` in [content.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content.php), [content-summary.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content-summary.php) and [index.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/index.php)
- `Permanent link to “%s”` in [functions.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/functions.php)
- (maybe these two above can be merged?)
- `'One response', '%d responses'` in [comments.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/comments.php)
- `'1 response', '%d responses'` in [content-single.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content-single.php), [content.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content.php) and [content-summary.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content-summary.php)
- (these two above might also be merged?)
- `'We found one result for “%2$s”', 'We found %1$s results for “%2$s”'` in [archive.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/archive.php) and [search.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/search.php)

Than there is one more string missing, which I thing should also converted to plural form.
- `See all %1$s posts by %2$s` in [content.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content.php) and [content-summary.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content-summary.php)

**Comment by craigcook** [comment]
PR #30 addresses these strings, hopefully. They were missed during extraction because I hadn't included '_n' or 'esc_attr__' as keywords. I also merged the strings you suggested and simplified the "see all X posts by Y" string by just removing the post count and avoiding the plural issue altogether. Please let me know if this is looking good or if I've missed something else (l10n is not my area of expertise, though I do try). Thanks for all your help!

**Comment by MikkCZ** [comment]
I looked at the PR and it includes all the strings mentioned above, but not their plural forms for `'1 response', '%d responses'` and `'We found one result for “%2$s”', 'We found %1$s results for “%2$s”'`. Not sure how the keywords work, but the .pot file it should look like
```
#: ...
msgid "1 response"
msgid_plural "%d responses"
msgstr[0] ""
msgstr[1] ""
```
In .po files the number of `msgstr[]` is language dependent.
- - -
I understand, I am not skilled in creating localizeable projects, only in the localization itself. As we use the theme on our community website, I am ready to report and fix the issues we found. But the "fix" part might take me some time.

**Comment by craigcook** [comment]
I've updated the PR. Today I learned about plural forms in gettext. Seems I was specifying the keyword the wrong way, and only entered "_n" when it should have been "_n:1,2"

**Comment by MikkCZ** [comment]
Yes, now it looks pretty good. The very last thing I noticed is fuzzy string
```
msgid "We found one result for “%2$s”"
msgid_plural "We found %1$s results for “%2$s”"
```
In all languages there's currently one translation for all plural forms and contains `%s` instead of `%1$s` and `%2$s`. Is it OK to let it marked as fuzzy, or better to delete the translations completely?

**Comment by MikkCZ** [comment]
Fixed by https://github.com/mozilla/One-Mozilla-blog/pull/30?

**Comment by craigcook** [comment]
Yes, I believe this is resolved. Thanks!
