### ISSUE TITLE
Edit Post button is hidden for single post view

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/One-Mozilla-blog#37]
In the posts list, the "Edit Post" button is placed under the post content in `<article>`.

But when you display the post standalone, the button is in `<header>` and overflowed by `<address>` and `<p class="entry-comments">`.

IMO placing the button there is OK, but should be better positioned and also definitely fully visible. Moving the button into the `<header>` in the list might be considered too.

**Comment by MikkCZ** [comment]
Or maybe into the articles `<footer>` for both views?

**Comment by MikkCZ** [comment]
@craigcook what do you think? I am ready to fix it.

**Comment by MikkCZ** [comment]
`<p class="entry-comments">` is in [content.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content.php), [content-single.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content-single.php) and [content-summary.php](https://github.com/mozilla/One-Mozilla-blog/blob/master/themes/OneMozilla/content-summary.php).

**Comment by craigcook** [comment]
I can't seem to reproduce this... the button clears the floats above it and appears on its own line. Can you point me to a URL where you're seeing it?

**Comment by MikkCZ** [comment]
It happens on Mozilla.cz, but unfortunately I cannot point you to any URL, as the "Edit post" button is shown to admins only. BUT I've quickly created a new instance of WordPress and it does not happen there... I don't know, how is that possible, as I was unable to find any difference in the applied styles for the button nor surrounding elements. I will try to test it more deeply, if it's not caused by some settings combination, and will add more details eventually or close the issue.

**Comment by MikkCZ** [comment]
I've been using older theme version. This has been fixed by https://github.com/mozilla/One-Mozilla-blog/commit/bff6a13ba1c7ab745ab531979f3d1fefced59233.
