### ISSUE TITLE
Swap older and newer posts link

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/One-Mozilla-blog#45]
The `Older posts` link should be on the right, not on the left. At least for me it's pretty unusual to have it on the left, as I read from top to bottom and left to right, so I expect the older articles will be on the bottom or on the right.

**Comment by craigcook** [comment]
The usual convention in LTR languages is that going left moves backward in time and going right moves forward in time (with the opposite for RTL languages). When you read left to right, everything you haven't read yet is always on the right, in the "future."

This is definitely made weird by the function names in WordPress. `next_posts_link()` fetches *older* posts and `previous_posts_link()` fetches *newer* posts, the opposite of what it should be if you think of a blog as a timeline (next should be future, previous should be past). They're treating it as pagination, not a timeline. WordPress also increments the page number in the URL, so higher numbered pages are showing older content from the past, backwards to what we're used to from reading books where higher numbered pages represent the future (and are on the right).

So I know it's odd when you look at the code or the URLs, but if you think about reading a blog as traveling through time, "Older posts" on the left makes sense.
