### ISSUE TITLE
Allow custom Tweet mention

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/One-Mozilla-blog#55]
Currently Tweet button will always use "via @firefox". This should be configurable in the settings to allow mentioning @FirefoxNightly or @MozillaCZ in our case.

@kyoshino would you be interested?

**Comment by kyoshino** [comment]
Where's the Tweet button?

**Comment by MikkCZ** [comment]
It can be enabled in the reading options. You can see it on http://www.mozilla.cz/zpravicky/zavadime-https/ when you click Share this.

**Comment by MikkCZ** [comment]
Sorry, it has been filed as https://github.com/mozilla/One-Mozilla-blog/issues/16 already. ;)
