### ISSUE TITLE
License

### ISSUE THREAD

**Issue by valerio-bozzolan** [mozilla/One-Mozilla-blog#58]
Sorry me, but if I'm not wrong it isn't possible to release a WordPress theme under licenses that are less strict than the GNU GPL, like the MPL 2.0.
https://wordpress.org/about/license/

Drupal's FAQs, that are more clear, can be used as similar guidelines:
https://www.drupal.org/about/licensing#q7

I think that the proper license can be choosed from one of:
* GNU GPL v2(+), v3(+)
* GNU AGPL v3(+)

https://www.gnu.org/licenses/license-list.html#MPL-2.0

**Comment by craigcook** [comment]
Interesting. Sounds like a theme is considered a derivative work since it interacts with WordPress, even if it's not code taken from WordPress. I'll get confirmation from the experts and see if we can switch to GPL.

**Comment by valerio-bozzolan** [comment]
(I think that it has sense. WordPress plugins and themes are so called because they live thanks to WordPress behind.)

Pherups "derivate work" is misleading. See "covered work" instead.

«A “covered work” means either the unmodified Program or a work based on the Program.»
https://www.gnu.org/licenses/gpl-3.0.html

**Comment by MikkCZ** [comment]
I am not a license wrangler, but @gerv was able to answer me similar questions in the past.

**Comment by gerv** [comment]
I think it's likely that most Wordpress themes are, in practice, derivative works of Wordpress. If there's no particular obstacle to GPLing it, that would be the safest route.

**Comment by craigcook** [comment]
Changed to GPLv3 in 0e2641ca311c823e1bac83dc3e7747640a51e744
