### ISSUE TITLE
Add co-author support to security blog

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/One-Mozilla-blog#59]
I am co-writing a blog post for https://blog.mozilla.org/security/ that is supposed to go out late next week.  Can co-author support be added to that blog?  Thanks!

**Comment by MikkCZ** [comment]
I am afraid this is not even supported by WordPress. But https://wordpress.org/plugins-wp/co-authors-plus/ might be the right think what you are looking for. @craigcook ?

**Comment by craigcook** [comment]
Added in https://github.com/mozilla/One-Mozilla-blog/commit/e15a0c952a41e4d287a55527bab8fca36ee7405f

**Comment by TanviHacks** [comment]
Thanks for adding the support Craig!  How do I add a co-author via the wordpress UI?  I can't seem to find any author or co-author UI in https://blog.mozilla.org/security/wp-admin/edit.php.

**Comment by craigcook** [comment]
Oops, you need Editor or higher access to assign a different author other than yourself. I've just promoted your account on the security blog so you should now see an Author field below the main editing area where you can add one or more co-authors. If you don't see an Author module on the page, check the "Screen Options" tab in the top right corner. That opens a drawer full of checkboxes to enable/disable various modules on the editing page. Make sure the "Author" box is checked and it should appear below.

Editors have access to more features than Authors and can modify or delete other people's posts, including content that's already been published, so be careful what you click on with your newly gained powers.

Also note that co-authors must also be registered users of the blog. If your co-author isn't registered on this particular blog we can add them. Or if they're not an employee with LDAP credentials, we can add them as a "Guest Author." Guest authors aren't actually registered users, they can't log in or post content, it's just a pseudo-user so we can give them a byline on posts we publish on their behalf.

Feel free to find me on IRC tomorrow if you need any help.

**Comment by TanviHacks** [comment]
Thanks Craig for adding me as an Editor and providing these instructions!

Can you add Peter Dolanjski as a registered user of the security blog?  He is Product Manager for Firefox and my co-author.  Thanks!

**Comment by craigcook** [comment]
> Can you add Peter Dolanjski as a registered user of the security blog?

Done!

**Comment by TanviHacks** [comment]
Thanks Craig!  I got it all working now!
