### ISSUE TITLE
Drop Open Sans and switch to Fira Sans

### ISSUE THREAD

**Issue by fitojb** [mozilla/One-Mozilla-blog#60]
https://mozilla.ninja/typography specifies the more readable Fira Sans for body text. Please switch to that.
(And to Zilla for headlines, once it becomes available.)

**Comment by craigcook** [comment]
This is in progress along with a few other design updates to suit the new branding. See https://bugzilla.mozilla.org/show_bug.cgi?id=1338672

**Comment by fitojb** [comment]
Oh, thanks for that link! :)

**Comment by craigcook** [comment]
Alas, revised brand guidelines have gone back to Open Sans. I'm still working on a rebranding of this theme, which will introduce the new Zilla font in some places, but Fira Sans is out for now. Which is sad because I really do love that font and find it much better than Open Sans.
