### ISSUE TITLE
Notice: add_custom_image_header is deprecated since version 3.4! 

### ISSUE THREAD

**Issue by MaykDQ** [mozilla/One-Mozilla-blog#7]
I tried to fix it but couldn’t
 line 50 on funtions.php :( using this:

``` php
add_theme_support( 'custom-header', array(
  // Header image default
  'default-image'     => get_template_directory_uri() . '/img/headers/firefox.png',
  // Header text display default
  'header-text'     => false,
  // Header image width (in pixels)
  'width'       => 340,
  // Header image height (in pixels)
  'height'      => 240
) );
```
http://make.wordpress.org/themes/2012/04/06/updating-custom-backgrounds-and-custom-headers-for-wordpress-3-4/

**Comment by MikkCZ** [comment]
Seems to be already fixed in https://github.com/mozilla/One-Mozilla-blog/commit/143b3d0c04fd3d40f0292a32d2c21cd8e1790987, where `add_custom_image_header()` is used only if not `version_compare( $wp_version, '3.4', '>=' )`.

**Comment by loganrosen** [comment]
Yep, I fixed it there. This can definitely be closed.
