### ISSUE TITLE
"Technology" link in Blog nav leads to unmaintained site

### ISSUE THREAD

**Issue by valgrimm** [mozilla/One-Mozilla-blog#74]
## Description
The "Technology" link in the navigation of the Mozilla Blog leads to an unmaintained site.

### Steps to reproduce
![techlink-unmaintained](https://user-images.githubusercontent.com/56933147/88692520-73b90f80-d0fe-11ea-9c15-5b66df1a01db.PNG)

### Expected result
Link should lead to a maintained site. 

### Actual result
Link leads to an unmaintained site

### Environment
Link does not depend on OS/platform/browser.

### Proposed resolution
Link 'Technology" to https://mozilla.dev/, which is maintained (and has a hard launch August 26).
As discussed with MJ Kelly and Justin Crawford via email on 27 July 2020.

**Comment by janbrasna** [comment]
@valgrimm @hoosteeno This is now resolved by redirecting all the old "Technology" links to future.mozilla.org for blogs that still use the default navigation masthead.

This is not exactly `@mozilla/one-mozilla-blog` issue, the navigation is part of `@craigcook/frontierline-theme` before https://github.com/craigcook/frontierline-theme/pull/64 update, now it can be customized and the default links have been updated too.

So whether anyone uses older theme version or not, this should now be fixed for everyone.

**Comment by craigcook** [comment]
Confirmed, this was actually regarding the Frontierline theme and has since been addressed (the One Mozilla theme doesn't have any built in navigation).
